"""Golden-screen exporter: the Rust rewrite oracle (docs/RUST_REWRITE_PLAN.md, Rule 1).

Boots the app over the same pinned environment as ``tests/test_snapshots.py``
(frozen clock, offline quote feed, seeded temp DB, relative paths), drives the
Watchlist inspector into its key states, and dumps each screen as JSON:
``rows × cells`` of ``{ch, fg, bg, attrs}`` with **resolved RGB** (theme token
blending happens before we read the styles, so the exported colors are the
colors a terminal would show).

Capture path: Textual 8's compositor — ``app.screen._compositor.render_strips()``
returns one :class:`~textual.strip.Strip` per row whose segments carry the
already-resolved ``rich.Style``. Nothing is monkeypatched beyond the offline
pins mirrored from ``snapshot_app``.

Scenario list: one module per screen under ``tests/golden_scenarios/``,
collected here in order. Each manifest entry carries the seed DB the Rust
harness renders against (``fixtures/golden_seed.db``, generated by
``tests/golden_seed.py``) and the tier the harness enforces: the declared
tier, except that the canonical 120x40 gates Tier A (the plan's R3 rule).

Usage::

    uv run python tests/export_golden.py --out fixtures/golden_screens
    uv run python tests/export_golden.py --state default --size 120x40 --out /tmp/g1
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest

sys.path.insert(0, str(Path(__file__).parent))  # conftest / test_tui imports

from conftest import seed_bars  # noqa: E402
from golden_scenarios import LIVE_SCENARIOS, SCENARIOS, Scenario  # noqa: E402
from test_tui import AAPL, FakeRig  # noqa: E402

from delta.asset_metrics import AssetMetrics  # noqa: E402
from delta.core.db import init_engine  # noqa: E402
from delta.tui.app import DeltaApp  # noqa: E402

NOW = datetime(2026, 9, 21, 9, 30, tzinfo=ZoneInfo("UTC"))
BAR_START = datetime(2026, 7, 3, tzinfo=UTC)
BAR_COUNT = 80

#: The seed DB every scenario renders against (repo-relative manifest path).
SEED = "fixtures/golden_seed.db"

#: The populated (``live-*``) world's config: both built-in markets, a chosen
#: model, the SEC plugin configured — everything the Settings screen shows.
POPULATED_CONFIG = {
    "base_currency": "AUD",
    "db_path": "delta.db",
    "reports_dir": "reports",
    "targets": {"apple": {"kind": "company", "market": "us", "tickers": ["AAPL"]}},
    "llm": {"provider": "openrouter", "model": "test-model"},
    "plugins": {"sec_edgar": {"enabled": True, "contact": "oracle@example.test"}},
    "markets": {
        "us": {"label": "United States", "currency": "USD", "yahoo_suffix": ""},
        "asx": {
            "label": "Australian Securities Exchange",
            "currency": "AUD",
            "yahoo_suffix": ".AX",
        },
    },
}

#: rich.Style boolean attributes recorded per cell (sorted in the output).
_STYLE_ATTRS = (
    "blink",
    "blink2",
    "bold",
    "conceal",
    "dim",
    "encircle",
    "frame",
    "italic",
    "overline",
    "reverse",
    "strike",
    "underline",
    "underline2",
)


def _price(i: int) -> float:
    return round(200.0 + i * 0.4 + 6 * math.sin(i / 4), 2)


def _metric() -> AssetMetrics:
    days = range(BAR_COUNT - 30, BAR_COUNT)
    series = [_price(i) for i in days]
    times = [(BAR_START + timedelta(days=i)).isoformat() for i in days]
    return AssetMetrics(
        AAPL.id,
        "equity",
        values={"Current price": f"{series[-1]:.2f}", "Market cap": "3.4T", "P/E": "31.2"},
        series=series,
        series_times=times,
        change_label=f"{(series[-1] / series[0] - 1) * 100:+.1f}%",
        history_start=times[0],
        history_end=times[-1],
        period_high=max(series),
        period_low=min(series),
    )


def _hex(color) -> str | None:
    """Resolved RGB for a rich Color, or None when the style inherits."""
    if color is None:
        return None
    triplet = color.triplet
    return f"#{triplet.red:02x}{triplet.green:02x}{triplet.blue:02x}"


def _capture_screen(app: DeltaApp) -> list[list[dict]]:
    """The visible screen as rows × cells of {ch, fg, bg, attrs}."""
    strips = app.screen._compositor.render_strips()
    rows: list[list[dict]] = []
    for strip in strips:
        row: list[dict] = []
        for segment in strip._segments:
            if segment.is_control:
                continue
            style = segment.style
            attrs = sorted(a for a in _STYLE_ATTRS if getattr(style, a, None))
            fg, bg = _hex(style.color), _hex(style.bgcolor)
            for ch in segment.text:
                row.append({"ch": ch, "fg": fg, "bg": bg, "attrs": attrs})
        rows.append(row)
    return rows


def export_scenario(scenario: Scenario, tmp_path: Path, out_dir: Path) -> Path:
    import shutil

    import time_machine
    import tomli_w

    from delta import tui
    from delta.core.config import build_config
    from delta.plugins.data.sec_edgar import SECEdgar
    from delta.quotes import YahooQuotes

    async def offline(self):
        self.on_state("offline test")
        await asyncio.Event().wait()

    populated = scenario.name.startswith("live-")
    seed_block: dict | None = None
    with pytest.MonkeyPatch.context() as mp:
        mp.setattr(YahooQuotes, "run", offline)
        mp.setattr(tui.screens.targets, "fetch_asset_metrics", lambda *a, **k: _metric())
        mp.setattr(
            "delta.tui.screens.config.read_env_value", lambda name: "test-key" if name else ""
        )
        mp.setattr("delta.tui.screens.config._human_size", lambda size: "4 KB")
        if populated:
            # The populated world: the shared seed DB is the store, and the
            # config carries every section the Settings screen renders.
            config = POPULATED_CONFIG
            tmp_path.joinpath("config.toml").write_text(tomli_w.dumps(config), "utf-8")
            shutil.copy2(Path(__file__).resolve().parent.parent / SEED, tmp_path / "delta.db")
            engine = init_engine(tmp_path / "delta.db")
            rig = FakeRig(engine, [AAPL.model_copy(update={"watchlists": ("apple",)})])
            rig.cfg = build_config(config)
            rig.plugins = {"sec_edgar": SECEdgar()}
            seed_block = {
                "version": 1,
                "now": NOW.isoformat(),
                "config": config,
                "provider_connected": True,
                "database_size": "delta.db · 4 KB",
            }
        else:
            tmp_path.joinpath("config.toml").write_text(
                tomli_w.dumps(
                    {"targets": {"apple": {"kind": "company", "market": "us", "tickers": ["AAPL"]}}}
                ),
                encoding="utf-8",
            )
            engine = init_engine(tmp_path / "delta.db")
            seed_bars(engine, AAPL.id, n=BAR_COUNT, start=BAR_START, price_fn=_price)
            rig = FakeRig(engine, [AAPL])
        rig.cfg.db_path = "delta.db"
        rig.cfg.reports_dir = "reports"
        import os

        old_cwd = Path.cwd()
        os.chdir(tmp_path)
        try:
            with time_machine.travel(NOW, tick=False):
                app = DeltaApp(rig)

                async def run() -> list[list[dict]]:
                    async with app.run_test(size=scenario.size) as pilot:
                        await pilot.press(*scenario.keys)
                        if scenario.name == "live-ask":
                            from delta.chat import ChatMessage
                            from delta.tui.screens.chat import Chat

                            with engine.connect() as connection:
                                turns = connection.exec_driver_sql(
                                    "SELECT role, text, citations, source FROM chatmessage ORDER BY seq"
                                ).all()
                            chat_screen = app.screen
                            assert isinstance(chat_screen, Chat)
                            chat_screen.history = [
                                ChatMessage(role=role, text=text, citations=tuple(json.loads(citations)), source=source)
                                for role, text, citations, source in turns
                            ]
                            chat_screen.selected_answer = len(chat_screen.history) - 1
                            await chat_screen._render_transcript()
                        # Workers (metrics fetch, refreshes) land over a few
                        # frames; mirror test_snapshots.py's run_before.
                        await pilot.pause(0.3)
                        return _capture_screen(app)

                rows = asyncio.run(run())
        finally:
            os.chdir(old_cwd)

    payload = {
        "state": scenario.name,
        "size": [scenario.size[0], scenario.size[1]],
        "tier": scenario.gate_tier,
        "rows": rows,
    }
    if seed_block is not None:
        payload["seed"] = seed_block
        payload["ui"] = {
            "keys": list(scenario.keys),
            "diagnostics_open": scenario.size[0] >= 100,
            "focus": "model",
            "selected_index": 0,
        }
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / scenario.filename
    path.write_text(
        json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8"
    )
    return path


def export_all(out_dir: Path, state: str | None = None, size: str | None = None) -> None:
    import tempfile

    everything = SCENARIOS + LIVE_SCENARIOS
    selected = [
        s
        for s in everything
        if (state is None or s.name == state or (state == "live" and s.name.startswith("live-")))
        and (size is None or s.size_label == size)
    ]
    if not selected:
        raise SystemExit(f"no scenario matches state={state!r} size={size!r}")
    files = []
    for scenario in selected:
        # Fresh seeded DB per scenario: the bars table has a UNIQUE(instrument, ts).
        td = Path(tempfile.mkdtemp())
        files.append(export_scenario(scenario, td, out_dir))
    manifest = {
        "seed": SEED,
        "scenarios": [
            {
                "state": s.name,
                "size": s.size_label,
                "tier": s.gate_tier,
                "file": s.filename,
                "seed": SEED,
            }
            for s in selected
        ],
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    # Populated scenarios are listed in their own manifest; the Rust harness
    # discovers screen states from it (a state is manifest + fixture, never
    # new harness code).
    manifest_name = (
        "live-manifest.json" if all(s.name.startswith("live-") for s in selected) else "manifest.json"
    )
    (out_dir / manifest_name).write_text(
        json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8"
    )
    for f in files:
        print(f"wrote {f}")


def test_golden_export_is_deterministic(tmp_path):
    """Exporting the same scenarios twice yields byte-identical JSON."""
    export_all(tmp_path / "a")
    export_all(tmp_path / "b")
    a = sorted(p.name for p in (tmp_path / "a").iterdir())
    b = sorted(p.name for p in (tmp_path / "b").iterdir())
    assert a == b and a
    for name in a:
        assert (tmp_path / "a" / name).read_bytes() == (tmp_path / "b" / name).read_bytes(), name


def test_live_settings_export_is_deterministic(tmp_path):
    """The populated Settings export is reproducible (seed block and rows)."""
    export_all(tmp_path / "a", state="live-settings", size="120x40")
    export_all(tmp_path / "b", state="live-settings", size="120x40")
    for name in ("live-settings-120x40.json", "live-manifest.json"):
        assert (tmp_path / "a" / name).read_bytes() == (tmp_path / "b" / name).read_bytes(), name


def test_live_settings_seed_describes_the_shared_world(tmp_path):
    """The populated fixture carries its config and points at the shared seed DB.

    The Rust live harness (crates/delta-tui/tests/live_golden.rs) rebuilds the
    screen state from the shared seed DB plus this seed block; everything the
    DB cannot hold (the config the exporter booted with, the frozen clock, the
    pinned database size) must therefore be embedded here.
    """
    export_all(tmp_path, state="live-settings", size="120x40")
    payload = json.loads((tmp_path / "live-settings-120x40.json").read_text(encoding="utf-8"))
    assert payload["state"] == "live-settings"
    assert payload["size"] == [120, 40]
    seed = payload["seed"]
    assert seed["version"] == 1
    assert seed["now"] == NOW.isoformat()
    assert seed["config"]["llm"] == {"provider": "openrouter", "model": "test-model"}
    assert seed["config"]["markets"]["asx"]["yahoo_suffix"] == ".AX"
    assert seed["config"]["plugins"]["sec_edgar"] == {
        "enabled": True,
        "contact": "oracle@example.test",
    }
    assert seed["provider_connected"] is True
    assert seed["database_size"] == "delta.db · 4 KB"
    assert payload["ui"]["keys"] == ["c"]
    assert payload["ui"]["diagnostics_open"] is True
    manifest = json.loads((tmp_path / "live-manifest.json").read_text(encoding="utf-8"))
    assert manifest["scenarios"] == [
        {"state": "live-settings", "size": "120x40", "tier": "A", "file": "live-settings-120x40.json", "seed": SEED}
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--state", help="scenario name (default: all)")
    parser.add_argument("--size", help="WxH filter (default: all)")
    parser.add_argument("--out", default="fixtures/golden_screens", help="output directory")
    args = parser.parse_args()
    export_all(Path(args.out), state=args.state, size=args.size)


if __name__ == "__main__":
    main()
