//! R3 golden-screen oracle, manifest-driven: reads
//! `fixtures/golden_screens/manifest.json` (state, size, tier and the seed DB
//! each scenario renders against), renders the scenario through the matching
//! painter, and diffs cell-for-cell against the exporter's JSON.
//!
//! Tier A: character, fg, bg, bold must match exactly — zero mismatches.
//! Tier B (prose): the text layer must be exact; colour differences are
//! printed as findings, not failures (docs/RUST_REWRITE_PLAN.md Rule 1).
//! On failure each differing row is printed side by side (want/got).

use std::path::{Path, PathBuf};

use delta_core::db::Db;
use delta_tui::braille::BrailleGraph;
use delta_tui::components::CommandPalette;
use delta_tui::dialog::{GoPicker, HelpDialog};
use delta_tui::screen::Screen;
use delta_tui::screens::{
    draw_ask, draw_ask_narrow, draw_ask_wide, draw_decisions, draw_decisions_narrow,
    draw_decisions_wide, draw_glossary_overlay, draw_home, draw_home_narrow, draw_home_wide,
    draw_research, draw_research_narrow, draw_research_wide, draw_settings, draw_settings_narrow,
    draw_settings_wide, draw_theses, draw_theses_narrow, draw_theses_wide, draw_watchlist,
    draw_watchlist_narrow, draw_watchlist_wide, grouped, HomeFeed, HomeState, MetricsData,
    WatchlistState,
};
use delta_tui::theme::Palette;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// One manifest entry: a scenario with its gate tier and seed DB.
struct Entry {
    state: String,
    size: (usize, usize),
    tier: String,
    file: String,
    seed: PathBuf,
}

fn manifest() -> Vec<Entry> {
    let raw = std::fs::read_to_string(repo_root().join("fixtures/golden_screens/manifest.json"))
        .expect("read fixtures/golden_screens/manifest.json");
    let value: serde_json::Value = serde_json::from_str(&raw).expect("parse manifest.json");
    value["scenarios"]
        .as_array()
        .expect("manifest scenarios")
        .iter()
        .map(|s| Entry {
            state: s["state"].as_str().expect("state").to_string(),
            size: {
                let size = s["size"].as_str().expect("size").to_string();
                let (w, h) = size.split_once('x').expect("WxH size");
                (w.parse().expect("width"), h.parse().expect("height"))
            },
            tier: s["tier"].as_str().expect("tier").to_string(),
            file: s["file"].as_str().expect("file").to_string(),
            seed: repo_root().join(s["seed"].as_str().expect("seed")),
        })
        .collect()
}

/// The shared seed DB (`fixtures/golden_seed.db`, generated by
/// `tests/golden_seed.py`): the harness reads bars and fundamentals from it
/// instead of rebuilding the exporter's data in Rust test code.
struct Seed {
    db: Db,
}

impl Seed {
    fn open(path: &Path) -> Self {
        assert!(path.exists(), "seed DB missing: {}", path.display());
        Self {
            db: Db::open(path).expect("open seed DB"),
        }
    }

    /// The exporter's `_metric()`: the last 30 bars of the inspected series.
    fn watchlist_state(&self, range: &'static str) -> WatchlistState {
        let bars = self.db.bars("US:AAPL").expect("seed bars for US:AAPL");
        assert!(bars.len() >= 30, "seed has the 80-bar AAPL series");
        let window = &bars[bars.len() - 30..];
        let values: Vec<f64> = window.iter().map(|b| b.close).collect();
        let times: Vec<String> = window
            .iter()
            .map(|b| format!("{}+00:00", b.ts.format("%Y-%m-%dT%H:%M:%S")))
            .collect();
        let current = grouped(values[values.len() - 1]);
        let change = (values[values.len() - 1] / values[0] - 1.0) * 100.0;
        let hi = values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        let lo = values.iter().cloned().fold(f64::INFINITY, f64::min);
        let metric_card = |name: &str| -> String {
            let value = self
                .db
                .fundamentals("US:AAPL")
                .expect("seed fundamentals")
                .iter()
                .find(|f| f.metric == name)
                .map(|f| f.value)
                .unwrap_or_else(|| panic!("seed fundamental {name} missing"));
            // The quoteSummary display form: one decimal, T for trillions.
            if value.abs() >= 1e12 {
                format!("{:.1}T", value / 1e12)
            } else {
                format!("{value:.1}")
            }
        };
        WatchlistState {
            range,
            metric: Some(MetricsData {
                symbol: "AAPL".to_string(),
                market: "us".to_string(),
                asset_class: "equity".to_string(),
                currency: "USD".to_string(),
                current,
                change_label: Some(format!("{change:+.1}%")),
                period_high: Some(hi),
                period_low: Some(lo),
                history_start: Some(times[0].clone()),
                history_end: Some(times[times.len() - 1].clone()),
                series: values.clone(),
                series_times: times,
                source: "Yahoo Finance".to_string(),
                values: vec![
                    (
                        "Current price".to_string(),
                        grouped(values[values.len() - 1]),
                    ),
                    ("Market cap".to_string(), metric_card("Market cap")),
                    ("P/E".to_string(), metric_card("P/E")),
                ],
            }),
        }
    }

    /// The exporter's home scenario: the last 40 closes drive table, spark.
    fn home_state(&self) -> HomeState {
        let bars = self.db.bars("US:AAPL").expect("seed bars for US:AAPL");
        assert!(bars.len() >= 40, "seed has the 80-bar AAPL series");
        let closes: Vec<f64> = bars[bars.len() - 40..].iter().map(|b| b.close).collect();
        let last = closes[closes.len() - 1];
        let prev = closes[closes.len() - 2];
        let chg_label = format!("{:+.2}%", (last / prev - 1.0) * 100.0);
        let spark = BrailleGraph::filled(closes.clone()).rows(17, 1)[0].clone();
        HomeState {
            // The frozen clock (2026-09-21 09:30 UTC) the goldens captured.
            clock: "Monday 21 September 2026 · 09:30:00 UTC".to_string(),
            symbol: "AAPL".to_string(),
            last: grouped(last),
            chg_label,
            spark,
            since_stamp: "since Mon 09:30".to_string(),
            closes,
            feed: HomeFeed::seed(),
        }
    }
}

fn watchlist_range(state: &str) -> &'static str {
    match state {
        "range-cycled" => "6m",
        _ => "1m",
    }
}

/// Render one scenario at its manifest size through the matching painter.
fn render(entry: &Entry, seed: &Seed) -> Screen {
    let (w, h) = entry.size;
    let state = entry.state.as_str();
    // The home-light state paints Home in delta-light; everything else is
    // dark.
    let palette = if state == "home-light" {
        Palette::Light
    } else {
        Palette::Dark
    };
    let mut screen = Screen::themed(palette, w, h);
    match state {
        "home" | "home-light" => match h {
            24 => draw_home_narrow(&mut screen, &seed.home_state()),
            40 => draw_home(&mut screen, &seed.home_state()),
            _ => draw_home_wide(&mut screen, &seed.home_state()),
        },
        "palette-open" => {
            paint_home(&mut screen, seed, h);
            CommandPalette::new().draw_screen(&mut screen);
        }
        "help-open" => {
            paint_home(&mut screen, seed, h);
            HelpDialog::default().draw_screen(&mut screen);
        }
        "go-open" => {
            paint_home(&mut screen, seed, h);
            GoPicker::draw_screen(&mut screen);
        }
        "default" | "range-cycled" | "narrow" => {
            let state = seed.watchlist_state(watchlist_range(&entry.state));
            match h {
                24 => draw_watchlist_narrow(&mut screen, &state),
                40 => draw_watchlist(&mut screen, &state),
                _ => draw_watchlist_wide(&mut screen, &state),
            }
        }
        "glossary" => draw_glossary_overlay(&mut screen, &seed.watchlist_state("1m")),
        "research" => match h {
            24 => draw_research_narrow(&mut screen),
            40 => draw_research(&mut screen),
            _ => draw_research_wide(&mut screen),
        },
        "theses" => match h {
            24 => draw_theses_narrow(&mut screen),
            40 => draw_theses(&mut screen),
            _ => draw_theses_wide(&mut screen),
        },
        "ask" => match h {
            24 => draw_ask_narrow(&mut screen),
            40 => draw_ask(&mut screen),
            _ => draw_ask_wide(&mut screen),
        },
        "decisions" => match h {
            24 => draw_decisions_narrow(&mut screen),
            40 => draw_decisions(&mut screen),
            _ => draw_decisions_wide(&mut screen),
        },
        "settings" => match h {
            24 => draw_settings_narrow(&mut screen),
            40 => draw_settings(&mut screen),
            _ => draw_settings_wide(&mut screen),
        },
        other => panic!("no Rust renderer for scenario state {other:?}; add one to golden.rs"),
    }
    screen
}

/// Home under the shell modals: the landing screen the exporter captured
/// them over.
fn paint_home(screen: &mut Screen, seed: &Seed, h: usize) {
    match h {
        24 => draw_home_narrow(screen, &seed.home_state()),
        40 => draw_home(screen, &seed.home_state()),
        _ => draw_home_wide(screen, &seed.home_state()),
    }
}

fn golden_path(entry: &Entry) -> PathBuf {
    repo_root()
        .join("fixtures/golden_screens")
        .join(&entry.file)
}

/// Row text (trimmed) as the exporter captured it, for the side-by-side diff.
fn row_text(row: &serde_json::Value) -> String {
    row.as_array()
        .expect("row")
        .iter()
        .map(|cell| {
            cell["ch"]
                .as_str()
                .unwrap_or(" ")
                .chars()
                .next()
                .unwrap_or(' ')
        })
        .collect::<String>()
        .trim_end()
        .to_string()
}

/// Cell-by-cell diff; Tier A returns colour+char mismatches, Tier B only
/// character mismatches (colour differences are logged findings instead).
fn diff(entry: &Entry, screen: &Screen, tier_a: bool) -> Vec<String> {
    let raw = std::fs::read_to_string(golden_path(entry))
        .unwrap_or_else(|e| panic!("read {}: {e}", entry.file));
    let value: serde_json::Value = serde_json::from_str(&raw).expect("parse golden JSON");
    let rows = value["rows"].as_array().expect("rows");
    assert_eq!(
        rows.len(),
        screen.h,
        "{}: golden height {} != rendered {}",
        entry.file,
        rows.len(),
        screen.h
    );
    let mut diffs = Vec::new();
    for (y, row) in rows.iter().enumerate() {
        for (x, cell) in row.as_array().expect("row").iter().enumerate() {
            let mine = &screen.cells[y * screen.w + x];
            let want_ch = cell["ch"].as_str().unwrap().chars().next().unwrap();
            if mine.ch != want_ch {
                diffs.push(format!(
                    "row {y} col {x}: want {want_ch:?} got {:?}",
                    mine.ch
                ));
                continue;
            }
            if !tier_a {
                continue;
            }
            let want = (
                cell["fg"].as_str(),
                cell["bg"].as_str(),
                cell["attrs"]
                    .as_array()
                    .expect("attrs")
                    .iter()
                    .any(|a| a == "bold"),
            );
            let got = (mine.fg, mine.bg, mine.bold);
            if got != want {
                diffs.push(format!("row {y} col {x}: want {want:?} got {got:?}"));
            }
        }
    }
    diffs
}

/// Side-by-side text diff of the rows that differ (the plan's fix-it output).
fn print_side_by_side(entry: &Entry, screen: &Screen) {
    let value: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(golden_path(entry)).unwrap_or_default())
            .expect("parse golden JSON");
    let rows = value["rows"].as_array().expect("rows");
    let mut printed = 0;
    for (y, row) in rows.iter().enumerate() {
        let want = row_text(row);
        let got: String = (0..screen.w)
            .map(|x| screen.cells[y * screen.w + x].ch)
            .collect::<String>()
            .trim_end()
            .to_string();
        if want != got {
            println!("{:>4} want |{want}|", "");
            println!("     got  |{got}|");
            printed += 1;
            if printed >= 12 {
                println!("     ... (side-by-side truncated at 12 rows)");
                return;
            }
        }
    }
}

/// Run one scenario under its manifest tier: Tier A fails on any mismatch;
/// Tier B fails only on text mismatches and logs colour findings.
fn run_scenario(entry: &Entry, seed: &Seed) {
    assert!(
        entry.seed.exists(),
        "seed DB missing for {}: {}",
        entry.file,
        entry.seed.display()
    );
    let screen = render(entry, seed);
    let tier_a = entry.tier == "A";
    let diffs = diff(entry, &screen, tier_a);
    if !diffs.is_empty() {
        print_side_by_side(entry, &screen);
    }
    if tier_a {
        assert!(
            diffs.is_empty(),
            "{}: {} Tier A mismatches\n{}",
            entry.file,
            diffs.len(),
            diffs.join("\n")
        );
    } else {
        assert!(
            diffs.is_empty(),
            "{}: {} Tier B text mismatches\n{}",
            entry.file,
            diffs.len(),
            diffs.join("\n")
        );
        let colour = diff_colours(entry, &screen);
        if !colour.is_empty() {
            println!(
                "{}: {} colour findings (Tier B, logged for triage):\n{}",
                entry.file,
                colour.len(),
                colour
                    .iter()
                    .take(30)
                    .cloned()
                    .collect::<Vec<_>>()
                    .join("\n")
            );
        }
    }
}

/// Tier B colour findings: cell differences where the characters already match.
fn diff_colours(entry: &Entry, screen: &Screen) -> Vec<String> {
    let value: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(golden_path(entry)).unwrap_or_default())
            .expect("parse golden JSON");
    let rows = value["rows"].as_array().expect("rows");
    let mut colour = Vec::new();
    for (y, row) in rows.iter().enumerate() {
        for (x, cell) in row.as_array().expect("row").iter().enumerate() {
            let mine = &screen.cells[y * screen.w + x];
            let want_ch = cell["ch"].as_str().unwrap().chars().next().unwrap();
            if mine.ch != want_ch {
                continue; // already reported as a text mismatch
            }
            let want = (
                cell["fg"].as_str(),
                cell["bg"].as_str(),
                cell["attrs"]
                    .as_array()
                    .expect("attrs")
                    .iter()
                    .any(|a| a == "bold"),
            );
            let got = (mine.fg, mine.bg, mine.bold);
            if got != want {
                colour.push(format!(
                    "row {y} col {x}: want {:?}/{:?}/b={} got {:?}/{:?}/b={}",
                    want.0, want.1, want.2, got.0, got.1, got.2
                ));
            }
        }
    }
    colour
}

/// Every manifest scenario must be rendered by some test; a scenario whose
/// state no test covers fails here, so new exports demand a Rust renderer.
fn assert_all_covered(entries: &[Entry], covered: &[&str]) {
    let missing: Vec<String> = entries
        .iter()
        .map(|e| e.state.clone())
        .filter(|s| !covered.contains(&s.as_str()))
        .collect();
    assert!(
        missing.is_empty(),
        "manifest states without a Rust renderer: {}",
        missing.join(", ")
    );
}

fn run_screen(entries: &[Entry], seed: &Seed, state: &str) {
    for entry in entries.iter().filter(|e| e.state == state) {
        run_scenario(entry, seed);
    }
}

#[test]
fn home_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "home");
    run_screen(&entries, &seed, "home-light");
    assert_all_covered(
        &entries,
        &[
            "home",
            "home-light",
            "default",
            "range-cycled",
            "narrow",
            "glossary",
            "research",
            "theses",
            "ask",
            "decisions",
            "settings",
            "palette-open",
            "help-open",
            "go-open",
        ],
    );
}

/// The R3.1a shell states: palette, help and Go modals over Home.
#[test]
fn shell_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    for state in ["palette-open", "help-open", "go-open"] {
        run_screen(&entries, &seed, state);
    }
}

#[test]
fn watchlist_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    for state in ["default", "range-cycled", "narrow", "glossary"] {
        run_screen(&entries, &seed, state);
    }
}

#[test]
fn research_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "research");
}

#[test]
fn theses_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "theses");
}

#[test]
fn ask_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "ask");
}

#[test]
fn decisions_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "decisions");
}

#[test]
fn settings_goldens() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    run_screen(&entries, &seed, "settings");
}

/// Compile-time guard: the seed DB must stay loadable by `delta_core::db::Db`
/// and hold the data the state builders read (bars + the two metric cards).
#[test]
fn seed_db_has_the_golden_data() {
    let entries = manifest();
    let seed = Seed::open(&entries[0].seed);
    let state = seed.watchlist_state("1m");
    let metric = state.metric.expect("inspector data");
    assert_eq!(metric.series.len(), 30);
    assert_eq!(metric.series_times[0], "2026-08-22T00:00:00+00:00");
    assert_eq!(
        metric.values[1],
        ("Market cap".to_string(), "3.4T".to_string())
    );
    assert_eq!(metric.values[2], ("P/E".to_string(), "31.2".to_string()));
    let home = seed.home_state();
    assert_eq!(home.closes.len(), 40);
}
